### ISSUE TITLE
Random command ID

### ISSUE THREAD

**Issue by mulderr** [arsalan0c/cdp-hs#62]
Hi,

do you accept issues/PRs at this point?

If so, in `CDP.Runtime`:

```
randomGen      <- newMVar . mkStdGen $ 42
(...)

randomCommandId :: Handle -> IO CommandId
randomCommandId handle = modifyMVar (randomGen handle) $ \g -> do
    let (id, g2) = uniformR (0 :: Int, 1000 :: Int) g
    pure (g2, CommandId id)
```

This isn't very randomy and repeats within the first 10 elements: `[560,663,95,783,208,466,913,535,651,95]`

However, instead of making it properly random, reading [this](https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md):

> Every command that is sent over to CDP must have a unique 'id' parameter. Message responses will be delivered over websocket and will have the same 'id'.

I'm wondering why have random ids at all? Maybe an `MVar Int` that starts at 1 and increments for each new command?

Puppeteer seems to [do just that](https://github.com/puppeteer/puppeteer/blob/f42336cf83982332829ca7e14ee48d8676e11545/packages/puppeteer-core/src/common/Connection.ts#L130).

**Comment by arsalan0c** [comment]
Thanks for pointing this out. A PR would be welcome!

Subscription ids for events are already implemented similarly, starting at 0 and incremented thereafter
https://github.com/arsalan0c/cdp-hs/blob/1346d4e70c97513716a6535d54ee8879f887645a/src/CDP/Internal/Utils.hs#L52
